comment:
  layout: "reach, diff, flags, files"
  behavior: new
  require_changes: false
  require_base: no
  require_head: yes

flags:
  go:
    paths:
      - "**/*.go"
    carryforward: true
  typescript:
    paths:
      - "ts/src/**"
    carryforward: true
