name: lint

on:
  # run on every push to main
  push:
    branches:
    - main
  # run on every push (not commit) to a PR, plus open/reopen
  # triggers for code changes in py files or changes to docs
  pull_request:
    types:
    - synchronize
    - opened
    - reopened
    paths:
      - '**.py'
      - docs/**

jobs:
  various:
    name: various (ruff formatting, ruff linting, mypy)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.13"
    - run: pip install .[lint]

    # annotate each step with `if: always` to run all regardless
    - name: Check code formatting with ruff
      if: always()
      run: ruff format --diff archeryutils/
    - name: Lint with ruff using pyproject.toml configuration
      if: always()
      run: ruff check archeryutils/
    - name: Type checking with mypy
      if: always()
      run: mypy archeryutils/
    - name: Check docs formatting with blackdoc
      if: always()
      run: blackdoc --diff docs/
