name: lint

on:
  # run on every push to main
  push:
    branches:
    - main
  # run on every push (not commit) to a PR, plus open/reopen
  pull_request:
    types:
    - synchronize
    - opened
    - reopened

jobs:
  various:
    name: various (Black, pylint, pydocstyle, mypy)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - run: pip install black pylint pydocstyle mypy
           pip install .[lint]

    # annotate each step with `if: always` to run all regardless
    - name: Assert that code matches Black code style
      if: always()
      uses: psf/black@stable
    - name: Lint with pylint
      if: always()
      run: pylint archeryutils/
    - name: Lint with pydocstyle
      if: always()
      run: pydocstyle --convention=numpy archeryutils/
    - name: Lint with mypy
      if: always()
      run: mypy archeryutils/
    - name: Check imports with isort
      if: always()
      uses: isort/isort-action@master
